### ISSUE TITLE
Questions for KM in January

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/PoolDilutionR#7]
In addition to #6 , and after merging #5 ...

* `optimize_pk` parameters - let's look carefully at these. Which if any should be in `params`?
* Right now it returns a list of stuff (basically the `optim` output with extra information). Maybe we also provide a `optimize_pk_tidy` function that returns a 1-row data frame?
* Naming of `P0` and `k0` is ugly
* Include test data in package, e.g. six samples from your dataset?
* Rename functions to follow a `pdr_xxxx` naming scheme?

**Comment by bpbond** [comment]
P.S. I'm focusing here because think we need the package stable before finalizing the science analysis.

**Comment by bpbond** [comment]
Also, we need a better mechanism so that users can let the optimizer fit `frac_P` and `frac_k` (as opposed to supplying fixed values currently); I had to kludge something ugly in https://github.com/COMPASS-DOE/grossMethane/pull/32 .

**Comment by kendalynnm** [comment]
Notes from JVF during AGU -
1) SD_precision in the denominator of the weighting variables should be instrument precision
2) Additional option for improving fits of problem samples - hold k steady and k0, fit P, then hold P steady at optimum and fit k

**Comment by bpbond** [comment]
I think we've addressed all these @kendalynnm ?
