### ISSUE TITLE
Co-working January 11th Notes

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/PoolDilutionR#8]
Goal: Allow users to vary 1 to 4 components (frac_P, frac_k, k, P)
Consequence: Warning to user about wisdom of varying all

Goal: Include function for calculating Nm and Nd with user providing SD_precision

Remaining tasks for package paper,
Example data, vignettes, housekeeping (documentation and tests)

Aspirational goal: Full rough draft by Fri. the 27th

**Comment by bpbond** [comment]
Re first goal see #9

**Comment by kendalynnm** [comment]
All items complete.
